inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/DoubleNegation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/DateTime:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolProc:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/EmptyLines:
  Enabled: true

Metrics/BlockLength:
  Exclude: 
    - test/**/*.rb
    - spec/**/*.rb

RSpec/DescribedClass:
  Enabled: false

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true
